services:
  - type: web
    name: gwindapp-materiais-backend
    env: node
    region: virginia
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: node start.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SMARTSHEET_ACCESS_TOKEN
        sync: false
      - key: PORT
        value: 4001

