services:
  - type: web
    name: gwindapp-materiais-backend
    env: node
    region: virginia
    plan: free
    buildCommand: npm install
    startCommand: node dist/index.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SMARTSHEET_ACCESS_TOKEN
        sync: false
      - key: PORT
        value: 4001

