services:
  - type: web
    name: gwindapp-materiais-backend
    env: node
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SMARTSHEET_TOKEN
        sync: false
      - key: SMARTSHEET_SHEET_MATERIAIS
        sync: false
      - key: SMARTSHEET_SHEET_MEDICOES
        sync: false
      - key: PORT
        value: 4001

